parameters:
    upload_directory: '%kernel.project_dir%/upload/files'
    domain_name: '%env(DOMAIN_NAME)%'
    database_name: '%env(DATABASE_NAME)%'
    smtp_address: '%env(SMTP_ADDRESS)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Business\SidebarBusiness:
        arguments:
            $directoryConfiguration: '%kernel.project_dir%/config/sidebar'



    Doctrine\Migrations\DependencyFactory: '@doctrine.migrations.dependency_factory'

    App\Business\UpgradeBusiness:
        arguments:
            $updateCode: '%env(UPDATE_CODE)%'

    App\Business\DatabaseBusiness:
        arguments:
            $withoutDatabaseConnection: '@doctrine.dbal.without_database_connection'